CURRENCY_INFO = {
    "USD": ("United States", "us.png"),
    "EUR": ("European Union", "eu.png"),
    "GBP": ("United Kingdom", "gb.png"),
    "INR": ("India", "in.png"),
    "JPY": ("Japan", "jp.png"),
    "AUD": ("Australia", "au.png"),
    "CAD": ("Canada", "ca.png"),
    "CHF": ("Switzerland", "ch.png"),
    "CNY": ("China", "cn.png"),
    "HKD": ("Hong Kong", "hk.png"),
    "NZD": ("New Zealand", "nz.png"),
    "SEK": ("Sweden", "se.png"),
    "KRW": ("South Korea", "kr.png"),
    "SGD": ("Singapore", "sg.png"),
    "NOK": ("Norway", "no.png"),
    "MXN": ("Mexico", "mx.png"),
    "RUB": ("Russia", "ru.png"),
    "ZAR": ("South Africa", "za.png"),
    "TRY": ("Turkey", "tr.png"),
    "BRL": ("Brazil", "br.png"),
    "TWD": ("Taiwan", "tw.png"),
    "DKK": ("Denmark", "dk.png"),
    "PLN": ("Poland", "pl.png"),
    "THB": ("Thailand", "th.png"),
    "IDR": ("Indonesia", "id.png"),
    "HUF": ("Hungary", "hu.png"),
    "CZK": ("Czech Republic", "cz.png"),
    "ILS": ("Israel", "il.png"),
    "CLP": ("Chile", "cl.png"),
    "PHP": ("Philippines", "ph.png"),
    "AED": ("United Arab Emirates", "ae.png"),
    "COL": ("Colombia", "co.png"),
    "SAR": ("Saudi Arabia", "sa.png"),
    "MYR": ("Malaysia", "my.png"),
    "RON": ("Romania", "ro.png"),
    "BGN": ("Bulgaria", "bg.png"),
    "HRK": ("Croatia", "hr.png"),
    "ISK": ("Iceland", "is.png"),
}